FROM envoyproxy/envoy-dev:latest

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

COPY ./ingress-envoy.yaml /etc/ingress-envoy.yaml

RUN chmod go+r /etc/ingress-envoy.yaml

CMD ["/usr/local/bin/envoy", "-c", "/etc/ingress-envoy.yaml", "--service-cluster", "ingress-proxy"]